---
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
additional_build_steps:
  prepend_base: |
    RUN for dir in \
        /home/runner \
        /home/runner/.ansible \
        /home/runner/.ansible/tmp \
        /runner \
        /home/runner \
        /runner/env \
        /runner/inventory \
        /runner/project \
        /runner/artifacts ; \
        do mkdir -m 0775 -p $dir ; chmod -R g+rwx $dir ; chgrp -R root $dir ; done && \
        for file in \
          /home/runner/.ansible/galaxy_token \
          /etc/passwd \
          /etc/group ; \
        do touch $file ; chmod g+rw $file ; chgrp root $file ; done
    RUN microdnf install python3-pip -y \
        && microdnf clean all
images:
  base_image:
    name: rockylinux:9.2-minimal
options :
  container_init:
    entrypoint: '["dumb-init", "--", "/opt/builder/bin/entrypoint"]'
    cmd: '["ansible-runner", "run", "/runner"]'
    package_pip: 'dumb-init'
  package_manager_path: /usr/bin/microdnf
  user: 'root'
